def shrek():
    print("          c,_.--.,y")
    print("            7 a.a(")
    print("           (   ,_Y)")
    print("           :  '---;")
    print("       ___.'\.  - (")
    print("     .''''S,._'--'_2..,_")
    print("     |    ':::::=:::::  \ ")
    print("     .     f== ;-,---.' T")
    print("      Y.   r,-,_/_      |")
    print("      |:\___.---' '---./")
    print("      |'`             )")
    print("       \             ,")
    print("       ':;,.________.;L")
    print("       /  '---------' |")
    print("       |              \ ")
    print("       L---'-,--.-'--,-'")
    print("        T    /   \   Y")
    print("        |   Y    ,   |")
    print("        |   \    (   |")
    print("        (   )     \,_L")
    print("        7-./      )  `,")
    print("       /  _(      '._  \ ")
    print("     '---'           '--'")